"""empty message

Revision ID: 3755350cb02d
Revises: e109dea798b6
Create Date: 2021-04-11 13:20:05.823569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3755350cb02d'
down_revision = 'e109dea798b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_type', sa.Column('no_of_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_type', 'no_of_days')
    # ### end Alembic commands ###
