"""empty message

Revision ID: 906e9d3b884b
Revises: fce68db8626d
Create Date: 2021-04-11 19:03:51.386709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906e9d3b884b'
down_revision = 'fce68db8626d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_type', 'custom_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_type', 'custom_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
