"""empty message

Revision ID: e109dea798b6
Revises: 6c7c34c9759e
Create Date: 2021-04-11 13:05:14.570553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e109dea798b6'
down_revision = '6c7c34c9759e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_type', sa.Column('minimum_charge', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_type', 'minimum_charge')
    # ### end Alembic commands ###
