"""empty message

Revision ID: fce68db8626d
Revises: 3755350cb02d
Create Date: 2021-04-11 18:18:48.217130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce68db8626d'
down_revision = '3755350cb02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_pricing',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_type', sa.Integer(), nullable=True),
    sa.Column('minimum_charge', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('no_of_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_type'], ['book_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book_type', sa.Column('custom_pricing', sa.Boolean(), nullable=True))
    op.drop_column('book_type', 'no_of_days')
    op.drop_column('book_type', 'minimum_charge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_type', sa.Column('minimum_charge', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('book_type', sa.Column('no_of_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('book_type', 'custom_pricing')
    op.drop_table('custom_pricing')
    # ### end Alembic commands ###
